# Generated by Django 5.0.7 on 2025-03-25 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='با کلیک بر روی دکمه اضافه کردن دسته بندی، می توانید دسته بندی های جدید را ایجاد کرده و همچنین با زدن تیک گزینه ایجاد زیر دسته، برای دسته بندی های ساخته شده یک زیر دسته ایجاد کنید!', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='home.category', verbose_name='ریر دسته'),
        ),
    ]
