# Generated by Django 5.0.7 on 2024-11-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='تلفن'),
        ),
    ]
